#!/usr/bin/env bash
docker-compose exec --user www-data app php occ config:system:set maintenance_window_start --type=integer --value=1
docker-compose exec --user www-data app php occ maintenance:repair --include-expensive
docker-compose exec --user www-data app php occ db:add-missing-indices
docker-compose exec --user www-data app php occ config:system:set default_phone_region gw
