#!/usr/bin/env bash
docker-compose exec --user www-data app php occ config:system:set maintenance_window_start --type=integer --value=1
docker-compose exec --user www-data app php occ maintenance:repair --include-expensive
docker-compose exec --user www-data app php occ db:add-missing-indices
docker-compose exec --user www-data app php occ config:system:set default_phone_region gw
docker-compose exec --user www-data app php occ config:system:set trusted_domains 3 --value=192.168.1.200

# Instala o Collabora Online server (como app do Nextcloud)
docker-compose exec --user www-data app php occ app:install richdocuments

# Instala o cliente Collabora Online (richdocumentscode)
docker-compose exec --user www-data app php occ app:install richdocumentscode

# Instala o Nextcloud Talk
docker-compose exec --user www-data app php occ app:install spreed

# Listar trusted_domains
docker-compose exec --user www-data app php occ config:system:get  trusted_domains
