version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    networks:
        redecloud:
          ipv4_address: 10.10.0.7
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: projetoaida
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
        redecloud:
          ipv4_address: 10.10.0.6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  redecloud:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16